### ISSUE TITLE
[Q] swag dependency

### ISSUE THREAD

**Issue by emicklei** [go-openapi/spec#154]
I just upgrade some dependencies in my project and I noticed that this package is now requiring `github.com/go-openapi/swag` which in turn causes many other dependencies to be included in my project. 

I expected a specification package to be and stay as minimal as possible.  WDYT?

**Comment by casualjim** [comment]
Swag has been included in spec for at least 2 years now. swag definitely won't be like strfmt which is a mess because of the mongodb stuff.

Which dependencies are not acceptable? 

* https://github.com/go-openapi/swag/blob/master/go.mod
* https://github.com/go-openapi/spec/blob/master/go.mod

We did add a `File` type to swag because it was the cause of a circular dependency in runtime, validate and loads

I wonder if the sourcegraph one is the one causing the friction. Would it be possible to be a bit more specific?

**Comment by emicklei** [comment]
I had a closer look at the swag package and realised it is not the swagger-ui package as I mistakenly assumed it was.
