### ISSUE TITLE
Enhancement: faster expander

### ISSUE THREAD

**Issue by fredbi** [go-openapi/spec#51]
While performing some intensive testing on go-openapi/validate I stumbled on test timeout issues...

Profiling the test case with pprof, it came out that about **half** the validation time is spent in expander.go, even though $ref expansion accounts but for a small amount of the overall test suite.

That's a *tremendous*-looking ratio, don't you think?

**Comment by casualjim** [comment]
before you do this :) I suggest you read the jsonref, jsonpointer and ref resolution specifications.
It's a very complex specification with a lot of cases that cause a lot of memory usage and so on.  

There are almost no implementations that actually do it correctly. AFAIK we're the one on go that handles most of the cases correctly.

**Comment by pytlesk4** [comment]
There has been a lot of changes recently to the spec package, so I will need to pull the latest into [this fork](https://github.com/stoplightio/spec). It caches the references, which speeds up that function pretty significantly. I made a pull request for the changes but closed it because it broke some tests in go-openapi/validate or go-openapi/analysis, I can try to make it again.

Also, what @casualjim said.

**Comment by kreamyx** [comment]
There is also another thing that might be causing the performance hit.
Validation is the only package that calls the exported ExpandSchema()
The exported ExpandSchema (unlike ExpandSchemaWithBase() and expandSchema()) doesn't take a basepath from which it can expand the refs that are inside that schema so temp files are created. 
This creation and deletion of temp files could be a performance issue and in fact unnecessary.
Since every call to validate, in theory, should be referencing a file, then validate should be calling the ExpandSchemaWithBase() and then we can get rid of ExpandSchema() and temp files completely.
That together with caching might increase performance if those were really the bottlenecks.

**Comment by fredbi** [comment]
Thanks guys. No  intent to start a war here! :blush:

Just wanted to share what my experience of the day inspired me.

- I *do* know that the culprit is the JSON schema specification, which caused (probably unintended) highly complex implementations
- I *do* know that almost no implementation is correct. It took me less than 10 min to figure out bugs even in a popular package like the nodeJS json-ref-parser. I think go-openapi does a good job (now)
- I am aware that this should probably not be a priority

Still, it was so frustrating to wait and eventually see my PR bashed because of a test timeout...:worried:

F.

**Comment by pytlesk4** [comment]
Sorry, I wasn't trying to bash your pull request, I don't even know what it is, just need to update my fork of this package. Really appreciate you trying to fix refs. It is a hard problem to say the least of it.

Just wanted to help out, refs are a really confusing.

**Comment by fredbi** [comment]
@pytlesk4  I was not referring about you: the Travis CI did bash it!

Looking forward to getting your improvements merged.

**Comment by pytlesk4** [comment]
@kreamyx removed the temp file creation and reading of the file. Also, if the ref just has a fragment only or is the root, then use the resolvers root to get what the ref is pointing at. Running the validate package tests was a lot faster.

**Comment by fredbi** [comment]
Thank you. You kept your word!

**Comment by kreamyx** [comment]
Great job @pytlesk4 !

**Comment by genexp** [comment]
Hi!  I just wanted to thank you for the work here.  Schema validation is the one slow test in our suite (it's about 8-12 seconds) and exactly what's been reported here is the problem.  Here's a flame graph you might find useful:

![screen shot 2018-02-15 at 2 48 46 pm](https://user-images.githubusercontent.com/816/36277613-5e9925be-125f-11e8-8c79-8945feaa1752.png)

**Comment by fredbi** [comment]
I think I may close this now.
There will always be some room for improvement, but latest PR did a great job.
